// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     demo:chat

package main

import (
        "runtime"
        "wit_component/export_demo_chat_handler"
witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
"unsafe"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (2*4), 4))
var syncExportPinner = runtime.Pinner{}


//go:wasmexport demo:chat/handler#handle
func wasm_export_demo_chat_handler_handle(arg0 uintptr, arg1 uint32) uintptr {
        
        pinner := &syncExportPinner
        value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
witRuntime.Unpin()
result := export_demo_chat_handler.Handle(value)
utf8 := unsafe.Pointer(unsafe.StringData(result))
pinner.Pin(utf8)
*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(result)))
*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
return exportReturnArea

        
}

//go:wasmexport cabi_post_demo:chat/handler#handle
func wasm_export_post_return_demo_chat_handler_handle(result uintptr) {
        syncExportPinner.Unpin()
}



// Unused, but present to make the compiler happy
func main() {}

