// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     demo:chat

package export_demo_chat_handler

import (
	"fmt"
	"strings"
)

// How much of the incoming message we quote back.
//
// This cap is what keeps the conversation from growing without bound: each
// participant quotes only a prefix of what it heard, so message length
// converges instead of compounding every turn.
const quoteChars = 44

// Handle implements the demo:chat/handler export.
//
// Its persona is a reverse-and-count: it reverses the quoted prefix and
// reports how many runes the original message contained.
func Handle(msg string) string {
	// Iterate by rune (code point) to avoid splitting multi-byte characters
	// or emoji. Go's range over string yields runes.
	runes := []rune(msg)
	head := runes[:min(len(runes), quoteChars)]

	// Reverse the head.
	var buf strings.Builder
	for i := len(head) - 1; i >= 0; i-- {
		buf.WriteRune(head[i])
	}

	total := len(runes)
	return buf.String() + fmt.Sprintf(" 🐹 (ʚ: %d runes)", total)
}
